---
AWSTemplateFormatVersion: '2010-09-09'
Description: Outer private & public subnet resources for veni

Parameters:
  StackName:
    Description: An Application name that will be prefixed to resource names
    Type: String
    Default: misc-stack
  Stage:
    Type: String
    
Resources:
  ECRRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${StackName}-ecr
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole' 

Outputs:
  ECRRepository:
    Description: Private subnet routetable one
    Value: !Ref 'ECRRepository'
    Export:
      Name: !Join [ '-', [ !Ref 'AWS::StackName', 'ecr' ] ]
 
