AWSTemplateFormatVersion: '2010-09-09'
Description: Root/Parent stack for veni infrastructure
Parameters:
  Stage:
    Type: String
Resources:
  UserWebAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/671e7d5a4a2ecdf3df6ab453cf92267c.template
      Parameters:
        StackName: user-webapp
        Stage:
          Ref: Stage
        AwsCertificateArn: arn:aws:acm:us-east-1:117468630787:certificate/a6f96f59-91f2-43a9-9204-72e2fb25cb26
        S3BucketName: user-webapp
        Domain: veni.buzz
        Route53HostedZoneName: veni.buzz.
        CloudFrontPriceClass: PriceClass_All
  RetailWebAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/671e7d5a4a2ecdf3df6ab453cf92267c.template
      Parameters:
        StackName: retail-webapp
        Stage:
          Ref: Stage
        AwsCertificateArn: arn:aws:acm:us-east-1:117468630787:certificate/c5c11580-5bc8-4736-8efe-97e7ccfd397b
        S3BucketName: retail-webapp
        Domain: veni.work
        Route53HostedZoneName: veni.work.
        CloudFrontPriceClass: PriceClass_All
  MiscStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/82a8a569b6f3dcea8efa4802908ef37f.template
      Parameters:
        Stage:
          Ref: Stage
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/acea0999250e4f567c23b895c985ed4e.template
      Parameters:
        Stage:
          Ref: Stage
  PublicSubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/7efe168b722acb992c3d8a1551f6b412.template
      Parameters:
        Stage:
          Ref: Stage
        PublicSubnet1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1
        PublicSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2
        PrivateSubnet1RouteTable:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1RouteTable
        PrivateSubnet2RouteTable:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2RouteTable
        ApiVPC:
          Fn::GetAtt:
          - VPCStack
          - Outputs.ApiVPC
  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/16cd90e9d41fe84847861444657e2ef7.template
      Parameters:
        Stage:
          Ref: Stage
        PrivateSubnet1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1
        PrivateSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2
        ApiVPC:
          Fn::GetAtt:
          - VPCStack
          - Outputs.ApiVPC
        ECSSecurityGroup:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.ECSSecurityGroup
  UserBFFStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/41382aac3413908e627f55dfa834c867.template
      Parameters:
        Stage:
          Ref: Stage
        PrivateSubnet1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1
        PrivateSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2
        ECRRepository:
          Fn::GetAtt:
          - MiscStack
          - Outputs.ECRRepository
        ECRURL:
          Fn::GetAtt:
          - MiscStack
          - Outputs.ECRURL
        ECSCluster:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.ECSCluster
        ECSSecurityGroup:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.ECSSecurityGroup
        UserBFFTargetGroup:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.UserBFFTargetGroup
        ExternalUrl:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.ExternalUrl
        HTTPSListener:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.HTTPSListener
