AWSTemplateFormatVersion: '2010-09-09'
Description: Root/Parent stack for veni infrastructure
Parameters:
  Stage:
    Type: String
Resources:
  UserWebAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/packaged-templates/671e7d5a4a2ecdf3df6ab453cf92267c.template
      Parameters:
        StackName: user-webapp
        Stage:
          Ref: Stage
        AwsCertificateArn: arn:aws:acm:us-east-1:117468630787:certificate/a6f96f59-91f2-43a9-9204-72e2fb25cb26
        S3BucketName: user-webapp
        Domain: veni.buzz
        Route53HostedZoneName: veni.buzz.
        CloudFrontPriceClass: PriceClass_All
  RetailWebAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/packaged-templates/671e7d5a4a2ecdf3df6ab453cf92267c.template
      Parameters:
        StackName: retail-webapp
        Stage:
          Ref: Stage
        AwsCertificateArn: arn:aws:acm:us-east-1:117468630787:certificate/c5c11580-5bc8-4736-8efe-97e7ccfd397b
        S3BucketName: retail-webapp
        Domain: veni.work
        Route53HostedZoneName: veni.work.
        CloudFrontPriceClass: PriceClass_All
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/packaged-templates/acea0999250e4f567c23b895c985ed4e.template
      Parameters:
        Stage:
          Ref: Stage
  PublicSubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/packaged-templates/0cfedff070853279d1d64f21c26e5e1b.template
      Parameters:
        Stage:
          Ref: Stage
        PublicSubnet1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1
        PublicSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2
        PrivateSubnet1RouteTable:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1RouteTable
        PrivateSubnet2RouteTable:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2RouteTable
        ApiVPC:
          Fn::GetAtt:
          - VPCStack
          - Outputs.ApiVPC
  PrivateSubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/packaged-templates/e243ff4a6683137c18651371c8922e81.template
      Parameters:
        Stage:
          Ref: Stage
        PrivateSubnet1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1
        PrivateSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2
        ApiVPC:
          Fn::GetAtt:
          - VPCStack
          - Outputs.ApiVPC
        ECSSecurityGroup:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.ECSSecurityGroup
  UserBFFStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/packaged-templates/fd628ee28775d7edd427d7d9b43e5712.template
      Parameters:
        Stage:
          Ref: Stage
        ApiVPC:
          Fn::GetAtt:
          - VPCStack
          - Outputs.ApiVPC
        PrivateSubnet1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1
        PrivateSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2
        ECSCluster:
          Fn::GetAtt:
          - PrivateSubnetStack
          - Outputs.ECSCluster
        ECSSecurityGroup:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.ECSSecurityGroup
        ExternalUrl:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.ExternalUrl
        HTTPSListener:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.HTTPSListener
        StackName: user-bff-stack
        ContainerPort: 443
        ServiceName: user-bff
        DllFile: user-bff.dll
        PathPattern: /user/*
        DesiredTaskCount: 1
        ListnerRulePriority: 1
  RetailBFFStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/packaged-templates/fd628ee28775d7edd427d7d9b43e5712.template
      Parameters:
        Stage:
          Ref: Stage
        ApiVPC:
          Fn::GetAtt:
          - VPCStack
          - Outputs.ApiVPC
        PrivateSubnet1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1
        PrivateSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2
        ECSCluster:
          Fn::GetAtt:
          - PrivateSubnetStack
          - Outputs.ECSCluster
        ECSSecurityGroup:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.ECSSecurityGroup
        ExternalUrl:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.ExternalUrl
        HTTPSListener:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.HTTPSListener
        StackName: retail-bff-stack
        ContainerPort: 444
        ServiceName: retail-bff
        DllFile: retail-bff.dll
        PathPattern: /retail/*
        DesiredTaskCount: 1
        ListnerRulePriority: 2
