AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Stage:
    Type: String
Resources:
  UserWebAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/3666b19dc2cd9ab682b97a160e71c4d7.template
      Parameters:
        StackName: user-webapp
        Stage:
          Ref: Stage
        AwsCertificateArn: arn:aws:acm:us-east-1:117468630787:certificate/a6f96f59-91f2-43a9-9204-72e2fb25cb26
        S3BucketName: user-webapp
        Domain: veni.buzz
        Route53Domain: veni.buzz.
        CloudFrontPriceClass: PriceClass_All
  RetailWebAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/3666b19dc2cd9ab682b97a160e71c4d7.template
      Parameters:
        StackName: retail-webapp
        Stage:
          Ref: Stage
        AwsCertificateArn: arn:aws:acm:us-east-1:117468630787:certificate/c5c11580-5bc8-4736-8efe-97e7ccfd397b
        S3BucketName: retail-webapp
        Domain: veni.work
        Route53Domain: veni.work.
        CloudFrontPriceClass: PriceClass_All
  MiscStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/0c166b21fd74850388047b4ed4ab5356.template
      Parameters:
        Stage:
          Ref: Stage
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/acea0999250e4f567c23b895c985ed4e.template
      Parameters:
        Stage:
          Ref: Stage
  PublicSubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/48958779d697fcd00014defd423103b7.template
      Parameters:
        Stage:
          Ref: Stage
        PublicSubnet1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1
        PublicSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2
        PrivateSubnet1RouteTable:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1RouteTable
        PrivateSubnet2RouteTable:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2RouteTable
        ApiVPC:
          Fn::GetAtt:
          - VPCStack
          - Outputs.ApiVPC
  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/16cd90e9d41fe84847861444657e2ef7.template
      Parameters:
        Stage:
          Ref: Stage
        PrivateSubnet1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1
        PrivateSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2
        ApiVPC:
          Fn::GetAtt:
          - VPCStack
          - Outputs.ApiVPC
        ECSSecurityGroup:
          Fn::GetAtt:
          - PublicSubnetStack
          - Outputs.ECSSecurityGroup
  UserBFFStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/nested-stack-bucket2/cdfa93e8962676c47d96f8945a6c4961.template
      Parameters:
        Stage:
          Ref: Stage
        PublicSubnet1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1
        PublicSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2
        ECRRepository: MiscStack.Outputs.ECRRepository
        ClusterName: PublicSubnetStack.Outputs.ClusterName
        ECSSecurityGroup: PublicSubnetStack.Outputs.ECSSecurityGroup
        UserBFFTargetGroup: PublicSubnetStack.Outputs.UserBFFTargetGroup
        ExternalUrl: PublicSubnetStack.Outputs.ExternalUrl
