AWSTemplateFormatVersion: '2010-09-09'
Description: Root/Parent stack for veni infrastructure

Parameters:
  Stage:
    Type: String

Resources:
  UserWebAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: generic-website-stack.yaml
      Parameters:
        StackName: user-webapp
        Stage: !Ref Stage
        AwsCertificateArn: arn:aws:acm:us-east-1:117468630787:certificate/a6f96f59-91f2-43a9-9204-72e2fb25cb26 #cert for veni.buzz
        S3BucketName: user-webapp
        Domain: veni.buzz
        Route53HostedZoneName: veni.buzz.
        CloudFrontPriceClass: PriceClass_All
  
  RetailWebAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: generic-website-stack.yaml
      Parameters:
        StackName: retail-webapp
        Stage: !Ref Stage
        AwsCertificateArn: arn:aws:acm:us-east-1:117468630787:certificate/c5c11580-5bc8-4736-8efe-97e7ccfd397b #cert for veni.work
        S3BucketName: retail-webapp
        Domain: veni.work
        Route53HostedZoneName: veni.work.
        CloudFrontPriceClass: PriceClass_All

  MiscStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: misc-stack.yaml
      Parameters:
        Stage: !Ref Stage

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc-stack.yaml
      Parameters:
        Stage: !Ref Stage
  
  PublicSubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: public-subnet-stack.yaml
      Parameters:
        Stage: !Ref Stage
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        PrivateSubnet1RouteTable: !GetAtt VPCStack.Outputs.PrivateSubnet1RouteTable
        PrivateSubnet2RouteTable: !GetAtt VPCStack.Outputs.PrivateSubnet2RouteTable
        ApiVPC: !GetAtt VPCStack.Outputs.ApiVPC

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: veni-db-stack.yaml
      Parameters:
        Stage: !Ref Stage
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        ApiVPC: !GetAtt VPCStack.Outputs.ApiVPC
        ECSSecurityGroup: !GetAtt PublicSubnetStack.Outputs.ECSSecurityGroup
  
  UserBFFStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: user-bff-stack.yaml
      Parameters:
        Stage: !Ref Stage
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        ECRRepository: !GetAtt MiscStack.Outputs.ECRRepository
        ECRURL: !GetAtt MiscStack.Outputs.ECRURL
        ECSCluster: !GetAtt PublicSubnetStack.Outputs.ECSCluster
        ECSSecurityGroup: !GetAtt PublicSubnetStack.Outputs.ECSSecurityGroup
        UserBFFTargetGroup: !GetAtt PublicSubnetStack.Outputs.UserBFFTargetGroup
        ExternalUrl: !GetAtt PublicSubnetStack.Outputs.ExternalUrl
        HTTPSListener: !GetAtt PublicSubnetStack.Outputs.HTTPSListener
